apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # firstapp
  POSTGRES_USER: Zmlyc3RhcHA=
  # password
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # firstappdb
  POSTGRES_DB: Zmlyc3RhcHBkYg==
